apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: home-alertmanager
  labels:
    alertmanager: home-alertmanager
spec:
  replicas: 2
  externalUrl: http://am.k8s.uda-cha.me
  alertmanagerConfigSelector:
    matchLabels:
      alertmanager: home-alertmanager
