apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: home-alertmanager
  labels:
    alertmanager: home-alertmanager
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 3h
    receiver: 'home-labo-slack'
  receivers:
  - name: 'home-labo-slack'
    slackConfigs:
    - apiURL:
        name: alertmanager-secret
        key: slackApiURL
      channel: '#home-labo'
      sendResolved: true
