apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vmware-exporter-servicemonitor
  labels:
    app.kubernetes.io/name: vmware-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmware-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
