apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: asia.gcr.io/cloud-proxy-291510/cloud_proxy@sha256:d60bbc7d543c5528577d878cd9c2f554b92fe7663a32d7f4f1702cf520e49315
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: cloud-proxy-gcr
