apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: asia.gcr.io/serotoninpower-gcr/cloud_proxy@sha256:fcfa03f967af905c6bed0810c3338f5c08a34f54baf279081197efa7b09e6ef5
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: serotoninpower-gcr
