apiVersion: v1
kind: Service
metadata:
  name: squid-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.220
  selector:
    app: squid
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
