apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service
  labels:
    app.kubernetes.io/name: vmware-exporter
spec:
  type: ClusterIP
  selector:
    app: vmware-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9272
    targetPort: 9272
