apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-alertmanager-ingress
spec:
  rules:
  - host: am.k8s.uda-cha.me
    http:
      paths:
      - backend:
          serviceName: home-alertmanager-service
          servicePort: 9093
