apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-alertmanager-ingress
spec:
  rules:
  - host: am.k8s.uda-cha.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: home-alertmanager-service
            port:
              number: 9093
