apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-exporter-ingress
spec:
  rules:
  - host: node-exporter.k8s.uda-cha.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: node-exporter-prometheus-service
            port:
              number: 9090
