apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: squid-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: squid.k8s.uda-cha.me
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: squid-service
                port:
                 number: 8080
