apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: squid-ingress
spec:
  rules:
    - host: squid.k8s.uda-cha.net
      http:
        paths:
          - backend:
              serviceName: squid-service
              servicePort: 8080
