apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: thanos-query
spec:
  rules:
  - host: thanos-query.k8s.uda-cha.net
    http:
      paths:
      - backend:
          serviceName: thanos-query-service
          servicePort: 9090
  - host: thanos-store.k8s.uda-cha.net
    http:
      paths:
      - backend:
          serviceName: thanos-store-service
          servicePort: 10902
  - host: thanos-compactor.k8s.uda-cha.net
    http:
      paths:
      - backend:
          serviceName: thanos-compactor-service
          servicePort: 10902
