apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-query
spec:
  rules:
  - host: thanos-query.k8s.uda-cha.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: thanos-query-service
            port:
              number: 9090
  - host: thanos-store.k8s.uda-cha.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: thanos-store-service
            port:
              number: 10902
  - host: thanos-compactor.k8s.uda-cha.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: thanos-compactor-service
            port:
              number: 10902
