apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vmware-exporter-ingress
spec:
  rules:
  - host: vmware-exporter.k8s.uda-cha.net
    http:
      paths:
      - backend:
          serviceName: vmware-exporter-prometheus-service
          servicePort: 9090
