apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmware-exporter-ingress
spec:
  rules:
  - host: vmware-exporter.k8s.uda-cha.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: vmware-exporter-prometheus-service
            port:
              number: 9090
