apiVersion: v1
kind: Service
metadata:
  name: home-dns-tcp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "home-dns-service"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.221
  selector:
    app: home-dns
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: home-dns-udp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "home-dns-service"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.221
  selector:
    app: home-dns
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
