apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: node-exporter
  labels:
    prometheus: node-exporter
spec:
  replicas: 2
  serviceAccountName: prometheus
  externalUrl: http://node-exporter.k8s.uda-cha.net
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
