apiVersion: v1
kind: Service
metadata:
  name: node-exporter-prometheus-service
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  - name: grpc
    port: 10901
    protocol: TCP
  selector:
    prometheus: node-exporter
