apiVersion: v1
kind: Service
metadata:
  name: node-exporter-outbound-service
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: node-exporter-outbound-service
  labels:
    app.kubernetes.io/name: node-exporter
subsets:
- addresses:
  - ip: 192.168.100.206
  ports:
  - name: metrics
    protocol: TCP
    port: 9100
