apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  type: ClusterIP
  selector:
    name: node-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9100
    targetPort: 9100
