apiVersion: v1
kind: Service
metadata:
  name: thanos-store-service
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
  - name: web
    port: 10902
    protocol: TCP
  selector:
    app: thanos-store
