apiVersion: v1
kind: Service
metadata:
  name: thanos-query-service
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
  - name: grpc
    port: 10901
    protocol: TCP
  selector:
    app: thanos-query
